### ISSUE TITLE
Darstellung Kundendaten bei Eingabe

### ISSUE THREAD

**Issue by YiskaCora** [Kamillendampf/bugReport#1]
Wenn ich Daten von Kunde eingebe, ist das Feld nicht scrollbar

**Comment by YiskaCora** [comment]
![image](https://github.com/Kamillendampf/bugReport/assets/163770858/f32856f9-6f18-4c4c-b087-5152e07cc89b)

**Comment by YiskaCora** [comment]
![image](https://github.com/Kamillendampf/bugReport/assets/163770858/9fc7ffb9-652c-45ce-8fc1-2de26f92dded)

**Comment by Kamillendampf** [comment]
Die Anzeige wird ab dem nächsten update nicht mehr so aussehen.
